
service: aws-cost-report-slack

provider:
  name: aws
  runtime: nodejs10.x

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'ce:GetCostAndUsage'
      Resource: '*'

plugins:
  - serverless-pseudo-parameters

functions:
  main:
    handler: index.handler
    memorySize: 128
    onError: ${opt:dlq, ''}

    events:
      - schedule: ${opt:schedule, self:custom.schedule.${self:custom.granularity}}

    environment:
      WEBHOOK_URL: ${opt:webhook-url}
      GRANULARITY: ${self:custom.granularity}

custom:
  schedule:
    DAILY: 'cron(30 0 * * ? *)'
    MONTHLY: 'cron(30 0 1 * ? *)'
  granularity: ${opt:granularity, 'DAILY'}
